import { countryInfo } from "./countryData";

type CountryCode = (typeof countryInfo)[number]["alpha-3"];
type BilateralRelation = [CountryCode, CountryCode, -1 | 1 | 0];

export const countries: Record<CountryCode, string> = {
  USA: "USA",
  RU: "Russia",
  UA: "Ukraine",
  UK: "United Kingdom",
  TR: "Turkey",
  TM: "Turkmenistan",
  SY: "Syria",
  // # "SY-K":"Syrian Kurds",
  // # "IQ-K":"Iraqi Kurds",
  IQ: "Iraq",
  GR: "Greece",
  EG: "Egypt",
  IS: "Israel",
  IR: "Iran",
  // # "IR-AZ":"Iran-Azerbaijanis",
  // # "IR-BL":"Iran-Balochis",
  "IR-MEK": "Iran-MEK",
  AL: "Algeria",
  MR: "Morocco",
  SADR: "Sahrawi",
  NK: "North Korea",
  SK: "South Korea",
  ZH: "PRC",
  "ZH-ETIM": "East Turkistan Islamic Movement",
  "ZH-TW": "ROC",
  JP: "Japan",
  "JP-RK": "Japan-Ryukyu (Okinawa)",
  MY: "Myanmar-Tatmadaw",
  "MY-NUG": "Myanmar-NUG",
  "MY-KAR": "Myanmar-Karen",
  "MY-RAK": "Myanmar-Rakhine",
  "MY-KAC": "Myanmar-Kachin",
  TH: "Thailand",
  QT: "Qatar",
  SR: "Serbia",
  KO: "Kosovo",
  "BiH-SR": "Bosnian Serb Entity",
  "BiH-CR": "Bosnian Croat Entity",
  AB: "Albania",
  NM: "FYROM",
  FJ: "Fiji",
  BG: "Bulgaria",
  MA: "Mali",
  "MA-TR": "Mali-Tuareg Rebels",
  FR: "France",
  // #"FR-GY":"French Guiana",
  // #"PM":"Panama",
  AZ: "Azerbaijan",
  AM: "Armenia",
  AH: "Artsakh",
  AR: "Argentina",
  CL: "Chile",
  "CL-RN": "Chile-Rapa Nui Pro-Independence",
  // #"UR":"Uruguay",
  // #"PU":"Peru",
  GY: "Guyana",
  // #"SN":"Suriname",
  SL: "Sri Lanka",
  "NG-BF": "Nigeria-Biafra",
  // #"GM":"Guam",
  // #"TK":"Tokelau",
  "CM-AM": "Cameroon-Ambazonia",
  CM: "Cameroon",
  IN: "India",
  SI: "Solomon Islands",
  "SI-M": "Solomon Islands - Malaita Rebels",
  PA: "Palestine",
  CY: "Cyprus",
  "CY-TRNC": "Cyprus TRNC",
  VZ: "Venezuela",
  CO: "Colombia",
  NI: "Nicaragua",
  NZ: "New Zealand",
  CU: "Cuba",
  AU: "Australia",
  PK: "Pakistan",
  "PK-BL": "Pakistan-Balochis",
  UAE: "Emirates",
  TN: "Tunisia",
  DRC: "DR Congo",
  "DRC-M23": "M23/Other Rebels",
  RW: "Rwanda",
  AG: "Afghanistan (Taliban)",
  "AG-BL": "Afghanistan-Balochis",
  "AG-PJ": "Afghanistan-Panjshiri Rebels",
  AN: "Angola",
  // #"BM":"Bahamas",
  BD: "Bangladesh",
  ET: "Ethiopia",
  "ET-TI": "Ethiopia-Tigray",
  SSD: "South Sudan",
  SU: "Sudan",
  "SU-P": "Sudan Protestors",
  TJ: "Tajikistan",
  KY: "Kyrgyzstan",
  IO: "Indonesia",
  "IO-WP": "Indonesia-West Papua",
  PNG: "Papua New Guinea",
  "PNG-BG": "Bougainville",
  KSA: "Saudi",
  "YM-H": "Houthi Rebels",
  YM: "Yemen (Sana'a)",
  PH: "Philippines",
  VN: "Viet Nam",
  BV: "Bolivia",
  BZ: "Belize",
  GT: "Guatemala",
  ML: "Maldives",
  MX: "Mexico",
  HT: "Haiti",
  HN: "Honduras",
  // #"EV":"El Salvador",
  MI: "Marshall Islands",
  // #"CH":"Chad",
  // #"CD":"Cambodia",
  NA: "Nauru",
  "FR-NC-PF": "Pro-France New Caledonia",
  "FR-NC-PI": "Pro-Independence New Caledonia",
  KB: "Kiribati",
  NR: "Niger",
  NG: "Nigeria",
  PL: "Palau",
  // #"CI":"Côte D'Ivoire",
  CR: "Croatia",
  EQ: "Equatorial Guinea",
  DR: "Dominican Republic",
  PR: "Paraguay",
  SKN: "St. Kitts & Nevis",
  SC: "St. Lucia",
  SV: "St. Vincent & Grenadines",
  TV: "Tuvalu",
  VA: "Vanuatu",
  LB: "Lebanon",
  "LB-HZ": "Lebanon-Hezbollah",
  // #"GH":"Ghana",
  FM: "Micronesia",
  SM: "Somalia",
  UG: "Uganda",
  CAR: "Central African Republic",
  KN: "Kenya",
  ABK: "Abkhazia",
  SOT: "South Ossetia",
  GE: "Georgia",
  MZ: "Mozambique",
  DJ: "Djibouti",
  SP: "Spain",
  FDLR: "FDLR Tutsi Militia",
  DN: "Denmark",
  ZW: "Zimbabwe",
  KZ: "Kazakhstan",
  "MO-TN": "Moldova-Transnistria",
  TZ: "Tanzania",
  // #"BN":"Burundi",
  // #"BF":"Burkina Faso",
  // #"TJ-IRPT":"Tajik Isl. Ren.",
  // #"TJ-PM-AG":"Tajik Aga-Khan",
  // #"TJ-PM-R":"Tajik Pamiri Rebels",
  "SM-SL": "Somaliland",
  "LB-TB": "Libya-Tobruk",
  "LB-TR": "Libya-Tripoli",
};
export const multilaterals = {
  NATO: "blue",
  OPEC: "blue",
  FRANCOSPHERE: "",
  OAS: "",
  ASEAN: "",
  MERCOSUR: "",
  EA: "",
  OPECPLUS: "blue",
  G7: "blue",
  G20: "blue",
  SCO: "teal",
  CSTO: "pink",
  BRICS: "green",
  OTS: "red",
  MUSLIMBROTHERHOOD: "lime",
  AFRICANUNION: "lime",
  ARABLEAGUE: "lime",
  COMMONWEALTH: "gold",
};
// # const connColors={
// #     -1:'tab:red',
// #     0:'black',
// #     1:'tab:blue',
// # }
export const connections: BilateralRelation[] = [
  ["GY", "SV", 1],
  ["SSD", "UG", 1],
  ["CM-AM", "NG-BF", 1],
  ["CM-AM", "CM", -1],
  ["NG-BF", "FR", 1],
  ["NG-BF", "UK", 1],
  ["NG-BF", "NG", -1],
  ["FR", "UA", 1],
  ["KZ", "RU", 0],
  ["KZ", "TR", 1],
  ["KZ", "AZ", 1],
  ["AZ", "GE", 1],
  ["KZ", "GE", 1],
  ["USA", "EQ", 1],
  ["TM", "ZH", 1],
  ["TM", "TR", 1],
  ["TM", "KZ", 1],
  ["TM", "AG", 1],
  ["TM", "KY", 1],
  ["USA", "ML", 1],
  ["SL", "ML", 1],
  ["KO", "ML", 1],
  ["ZH", "ML", 1],
  ["IN", "ML", 1],
  ["IN", "MR", 1],
  ["AZ", "LB-TB", 1],
  ["SI", "SI-M", -1],
  ["ZH-TW", "SI-M", 1],
  ["FR", "FR-NC-PI", -1],
  ["FR", "FR-NC-PF", 1],
  ["LB-HZ", "LB", 0],
  ["LB-HZ", "IR", 1],
  ["LB-HZ", "IS", -1],
  ["LB-HZ", "PA", 1],
  ["CL-RN", "CL", -1],
  ["PA", "CL", 1],
  ["PNG-BG", "FJ", 1],
  ["PNG-BG", "SI", 1],
  ["ZH", "FJ", 1],
  ["NZ", "FJ", -1],
  ["AU", "FJ", -1],
  ["MR", "USA", 1],
  ["CAR", "RU", 1],
  ["AZ", "AH", -1],
  ["AM", "AH", 1],
  ["JP", "PL", 1],
  ["JP", "ZH-TW", 1],
  ["RU", "AH", 1],
  ["MO-TN", "AH", 1],
  ["RU", "MO-TN", 1],
  ["SOT", "MO-TN", 1],
  ["ABK", "MO-TN", 1],
  ["ABK", "SOT", 1],
  ["ABK", "AH", 1],
  ["SOT", "AH", 1],
  ["ABK", "SY", 1],
  ["SOT", "SY", 1],
  ["ABK", "NA", 1],
  ["SOT", "NA", 1],
  ["ABK", "NI", 1],
  ["SOT", "NI", 1],
  ["ABK", "VZ", 1],
  ["SOT", "VZ", 1],
  ["ABK", "RU", 1],
  ["SOT", "RU", 1],
  ["USA", "GE", 1],
  ["ABK", "GE", -1],
  ["SOT", "GE", -1],
  ["SADR", "VA", 1],
  ["SADR", "VN", 1],
  ["SADR", "RW", 1],
  ["SADR", "NK", 1],
  ["SADR", "SOT", 1],
  ["SADR", "ABK", 1],
  ["DN", "SM-SL", 1],
  ["SM", "KO", 1],
  ["DJ", "KO", 1],
  ["DJ", "SM-SL", 1],
  ["UAE", "SM-SL", 1],
  ["ET", "SM-SL", 1],
  ["KN", "SM-SL", 1],
  ["PK-BL", "PK", -1],
  ["PK-BL", "ZH", -1],
  // # ["IR-BL","IR",-1],
  ["AG-BL", "AG", -1],
  ["TR", "SM-SL", 1],
  ["SM", "SM-SL", 0],
  ["SM", "USA", 1],
  ["ZH-TW", "SM-SL", 1],
  ["ZH-TW", "BZ", 1],
  ["ZH-TW", "GT", 1],
  ["ZH-TW", "HT", 1],
  ["EG", "TZ", 1],
  ["ZH", "TZ", 1],
  ["ZH-TW", "HN", 1],
  ["NZ", "KB", 1],
  ["SP", "KO", -1],
  ["EG", "KO", 1],
  ["NI", "KO", 1],
  ["CY", "KO", -1],
  ["SP", "KSA", 1],
  ["VN", "KO", -1],
  ["UA", "KO", -1],
  ["AR", "KO", -1],
  ["AM", "KO", -1],
  ["AZ", "KO", -1],
  ["IN", "KO", -1],
  ["ZH-TW", "KO", 1],
  ["ZH", "NZ", 0],
  ["AU", "NZ", 1],
  ["AU", "KB", 1],
  ["AU", "PL", 1],
  ["AU", "FM", 1],
  ["KO", "SI", -1],
  ["KO", "CAR", -1],
  ["KO", "PNG", -1],
  ["KO", "FM", 1],
  ["KO", "VA", 1],
  ["AU", "VA", 1],
  ["IO-WP", "VA", 1],
  ["USA", "PL", 1],
  ["USA", "FM", 1],
  ["USA", "DR", 1],
  ["USA", "MI", 1],
  ["ZH-TW", "MI", 1],
  ["ZH-TW", "NA", 1],
  ["USA", "JP-RK", -1],
  ["IR", "MA", 1],
  // # ["AZ","IR-AZ",1],
  // # ["IR","IR-AZ",-1],
  ["IR", "KSA", -1],
  ["KO", "DN", 1],
  ["KO", "NA", -1],
  ["AU", "NA", 1],
  ["ZH-TW", "PL", 1],
  ["ZH-TW", "PR", 1],
  ["KO", "SKN", 1],
  ["ZH-TW", "SKN", 1],
  ["KO", "SC", 1],
  ["KO", "NI", 1],
  ["KO", "NG", -1],
  ["KO", "ZH", -1],
  ["KO", "TV", 1],
  ["KO", "BD", 1],
  ["ZH-TW", "SC", 1],
  ["ZH-TW", "SV", 1],
  ["ZH-TW", "TV", 1],
  ["BV", "RU", 1],
  ["BV", "VZ", 1],
  ["BV", "CU", 1],
  ["TH", "USA", 0],
  ["TJ", "PK", 1],
  ["TJ", "AG", -1],
  ["AG-PJ", "AG", -1],
  ["AG-PJ", "USA", 1],
  ["AG", "RU", 1],
  ["NR", "FR", 1],
  ["NR", "MA", -1],
  ["TH", "ZH", 0],
  ["AU", "IO", 1],
  ["USA", "AM", 1],
  ["USA", "AZ", 1],
  ["BG", "GR", 1],
  ["PNG", "IO", 1],
  ["MI", "IO-WP", 1],
  ["NA", "IO-WP", 1],
  ["PL", "IO-WP", 1],
  ["TV", "IO-WP", 1],
  ["VA", "IO-WP", 1],
  ["SI", "IO-WP", 1],
  ["IO", "IO-WP", -1],
  ["AU", "UA", 1],
  ["TJ", "KY", -1],
  ["TJ", "IR", 1],
  ["KY", "TR", 1],
  ["TJ", "TR", 1],
  ["AU", "ZH", -1],
  ["ZH", "SI", 1],
  ["FR-NC-PI", "SI", 1],
  ["PA", "QT", 1],
  ["AU", "SI", 0],
  ["AU", "USA", 1],
  ["USA", "IS", 1],
  ["IR", "IS", -1],
  ["USA", "CU", -1],
  ["USA", "VZ", -1],
  ["USA", "NI", -1],
  ["USA", "CO", 1],
  ["VZ", "CO", 1],
  ["VZ", "CU", 1],
  ["VZ", "NI", 1],
  ["VZ", "IR", 1],
  ["CU", "NI", 1],
  ["CU", "TR", 1],
  ["CU", "ZH", 1],
  ["NM", "GR", -1],
  ["NM", "BG", -1],
  ["USA", "MY-NUG", 1],
  ["MY", "MY-NUG", -1],
  ["UK", "RU", -1],
  ["MY", "RU", 1],
  ["IR-MEK", "IR", -1],
  ["IR-MEK", "AB", 1],
  ["KO", "AB", 1],
  ["KO", "GR", -1],
  ["KO", "RU", -1],
  ["TR", "AB", 1],
  ["IR", "AB", -1],
  ["IS", "PA", -1],
  ["IR", "PA", 1],
  ["KO", "QT", 1],
  ["KO", "GY", 1],
  ["KO", "IS", 1],
  ["AZ", "IS", 1],
  ["KSA", "USA", 1],
  ["KSA", "YM", 1],
  ["MA", "FR", -1],
  ["AM", "FR", 1],
  ["USA", "FR", 1],
  ["UK", "FR", 0],
  ["MA", "MA-TR", -1],
  ["MY", "MY-KAR", -1],
  ["MY", "MY-RAK", -1],
  ["MY", "MY-KAC", -1],
  ["MA", "RU", 1],
  ["IS", "GR", 1],
  ["CY", "GR", 1],
  ["CY-TRNC", "AZ", 1],
  ["CY-TRNC", "TR", 1],
  ["CY-TRNC", "CY", -1],
  ["UAE", "YM", 1],
  ["YM-H", "YM", -1],
  ["YM-H", "UAE", -1],
  ["YM-H", "KSA", -1],
  ["YM-H", "IR", 1],
  ["DRC", "DRC-M23", -1],
  ["RW", "USA", 1],
  ["RW", "DRC-M23", 1],
  ["RW", "DRC", -1],
  ["RW", "FDLR", -1],
  ["USA", "GR", 1],
  ["KO", "SR", -1],
  ["RU", "SR", 1],
  ["BiH-SR", "BiH-CR", -1],
  ["CR", "BiH-CR", 1],
  ["BiH-SR", "SR", 1],
  ["KO", "USA", 1],
  ["UAE", "IS", 1],
  ["UAE", "IR", -1],
  ["KO", "IR", -1],
  ["USA", "IR", -1],
  ["USA", "VN", 1],
  ["USA", "AG", -1],
  ["USA", "ZW", -1],
  ["ZH", "ZW", 1],
  ["UK", "TR", 1],
  ["UK", "ZW", -1],
  ["RU", "VN", 1],
  ["USA", "PH", 1],
  ["PH", "RU", 1],
  ["PH", "ZH", -1],
  ["EG", "ET", -1],
  ["UAE", "ET", 1],
  ["SSD", "ET", 1],
  ["SSD", "USA", 1],
  ["ET-TI", "ET", -1],
  ["ET-TI", "USA", 1],
  ["EG", "GR", 1],
  ["TN", "AL", 1],
  ["SU-P", "SU", -1],
  ["KO", "SU", -1],
  ["UA", "USA", 1],
  ["SU-P", "USA", 1],
  ["AL", "SADR", 1],
  ["MR", "SADR", -1],
  ["AL", "MR", -1],
  ["AL", "RU", 1],
  ["MR", "IS", 1],
  ["IR", "RU", 1],
  ["IN", "AM", 1],
  ["PK", "AM", -1],
  ["PK", "IN", -1],
  ["RU", "IN", 1],
  ["PK", "AZ", 1],
  ["IR", "AM", 1],
  ["AZ", "AM", -1],
  ["AZ", "TR", 1],
  ["UA", "FR", 1],
  ["UA", "TR", 1],
  ["UA", "RU", -1],
  ["USA", "RU", -1],
  ["TR", "GR", -1],
  ["TR", "EG", 1],
  ["SY", "USA", -1],
  ["SY", "IR", 1],
  // # ["SY-K","SY",-1],
  // # ["SY-K","USA",1],
  // # ["SY-K","TR",-1],
  // # ["SY-K","IR",-1],
  // # ["IQ-K","IQ",0],
  ["IQ-K", "SY-K", 1],
  // # ["IQ-K","TR",-1],
  ["PK", "IR", 1],
  ["IN", "IR", 1],
  // # ["IQ-K","IR",-1],
  // # ["IQ-K","USA",1],
  ["SY", "RU", 1],
  ["SY", "IS", -1],
  ["LB-TB", "LB-TR", -1],
  ["LB-TR", "TR", 1],
  ["LB-TR", "QT", 1],
  ["LB-TR", "PK", 1],
  ["LB-TR", "IR", 1],
  ["LB-TR", "MR", 1],
  ["LB-TR", "AL", 1],
  ["LB-TB", "GR", 1],
  ["LB-TB", "EG", 1],
  ["LB-TB", "UAE", 1],
  ["LB-TB", "SY", 1],
  ["LB-TB", "KSA", 1],
  ["LB-TB", "FR", 1],
  ["LB-TB", "RU", 1],
  ["KO", "CR", 1],
  ["KO", "CM", -1],
  ["KO", "DRC", -1],
  ["KO", "AR", -1],
  ["KO", "ZH-ETIM", 1],
  ["KO", "BZ", 1],
  ["KO", "MI", 1],
  ["ZH", "SR", 1],
  ["ZH", "IN", -1],
  ["KO", "IN", -1],
  ["KO", "PK", 1],
  ["KO", "NM", 1],
  ["IS", "TR", 1],
  ["ZH", "RU", 1],
  ["ZH", "NK", 1],
  ["ZH", "ZH-ETIM", -1],
  ["ZH", "ZH-TW", -1],
  ["USA", "ZH-ETIM", 1],
  ["USA", "ZH-TW", 1],
  ["USA", "ZH", -1],
  ["USA", "NK", -1],
  ["RU", "NK", 1],
  ["USA", "SK", 1],
  ["NK", "SK", -1],
  ["NK", "JP", -1],
  ["HT", "DR", -1],
  ["CU", "MX", 1],
  ["BD", "PK", -1],
  ["BD", "MY", 1],
  ["AG", "UAE", 1],
  ["ZH", "EQ", 1],
  ["PNG", "AU", 1],
  ["PA", "ZH", 1],
  ["QT", "ZH", 1],
  ["IR", "ZH", 1],
  ["UAE", "ZH", 1],
  ["UAE", "SU", 1],
  ["MZ", "AN", 1],
  ["MZ", "UG", 1],
  ["MZ", "USA", 1],
  ["MZ", "RU", 1],
  ["MZ", "RW", 1],
  ["CAR", "RW", 1],
  ["KSA", "ZH", 1],
  ["PNG", "ZH", 1],
  ["PNG", "PNG-BG", -1],
  ["SK", "JP", 1],
  ["VZ", "GY", -1],
];
