import { countryInfo } from "./countryData";

type CountryCode = (typeof countryInfo)[number]["alpha-3"];
export type BilateralRelation = [CountryCode, CountryCode, -1 | 1 | 0];

export const countries: { [code in CountryCode]?: string } = {
  USA: "USA",
  RUS: "Russia",
  UKR: "Ukraine",
  GBR: "United Kingdom",
  TUR: "Turkey",
  TKM: "Turkmenistan",
  SYR: "Syria",
  //   # "SYR-K":"Syrian Kurds",
  //   # "IRQ-K":"Iraqi Kurds",
  IRQ: "Iraq",
  GRC: "Greece",
  EGY: "Egypt",
  ISR: "Israel",
  IRN: "Iran",
  //   # "IRN-AZE":"Iran-Azerbaijanis",
  //   # "IRN-BL":"Iran-Balochis",
  // //   "IRN-MEK": "Iran-MEK",
  DZA: "Algeria",
  MAR: "Morocco",
  ESH: "Sahrawi",
  PRK: "North Korea",
  KOR: "South Korea",
  CHN: "PRC",
  //   "CHN-ETIM": "East Turkistan Islamic Movement",
  TWN: "ROC",
  JPN: "Japan",
  // //   "JPN-RK": "Japan-Ryukyu (Okinawa)",
  MMR: "Myanmar-Tatmadaw",
  // //   "MMR-NUG": "Myanmar-NUG",
  // //   "MMR-KAR": "Myanmar-Karen",
  // //   "MMR-RAK": "Myanmar-Rakhine",
  // //   "MMR-KAC": "Myanmar-Kachin",
  THA: "Thailand",
  QAT: "Qatar",
  SRB: "Serbia",
  //   KO: "Kosovo",
  //   "BiH-SRB": "Bosnian Serb Entity",
  //   "BiH-HRV": "Bosnian Croat Entity",
  ALB: "Albania",
  MKD: "FYROM",
  FJI: "Fiji",
  BGR: "Bulgaria",
  MLI: "Mali",
  // //   "MLI-TUR": "Mali-Tuareg Rebels",
  FRA: "France",
  //   #"FRA-GUY":"French Guiana",
  // #"PM":"Panama",
  AZE: "Azerbaijan",
  ARM: "Armenia",
  //   AH: "Artsakh",
  ARG: "Argentina",
  CHL: "Chile",
  // // //   "CHL-RN": "Chile-Rapa Nui Pro-Independence",
  // #"UR":"Uruguay",
  PER: "Peru",
  GUY: "Guyana",
  // #"SN":"Suriname",
  LKA: "Sri Lanka",
  // //   "NGA-BF": "Nigeria-Biafra",
  // #"GM":"Guam",
  // #"TK":"Tokelau",
  // //   "CMR-ARM": "Cameroon-Ambazonia",
  CMR: "Cameroon",
  IND: "India",
  SLB: "Solomon Islands",
  // //   "SLB-M": "Solomon Islands - Malaita Rebels",
  PSE: "Palestine",
  CYP: "Cyprus",
  //   "CYP-TRNC": "Cyprus TRNC",
  VEN: "Venezuela",
  COL: "Colombia",
  NIC: "Nicaragua",
  NZL: "New Zealand",
  CUB: "Cuba",
  AUS: "Australia",
  PAK: "Pakistan",
  // //   "PAK-BL": "Pakistan-Balochis",
  ARE: "Emirates",
  TUN: "Tunisia",
  COD: "DOM Congo",
  //   "COD-M23": "M23/Other Rebels",
  RWA: "Rwanda",
  AFG: "Afghanistan (Taliban)",
  // //   "AFG-BL": "Afghanistan-Balochis",
  // //   "AFG-PJ": "Afghanistan-Panjshiri Rebels",
  AGO: "Angola",
  // #"BM":"Bahamas",
  BGD: "Bangladesh",
  ETH: "Ethiopia",
  // //   "ETH-TI": "Ethiopia-Tigray",
  SSD: "South Sudan",
  SDN: "Sudan",
  //   "SDN-P": "Sudan Protestors",
  TJK: "Tajikistan",
  KGZ: "Kyrgyzstan",
  IDN: "Indonesia",
  // //   "IDN-WP": "Indonesia-West Papua",
  PNG: "Papua New Guinea",
  //   "PNG-BGR": "Bougainville",
  SAU: "Saudi",
  //   "YEM-H": "Houthi Rebels",
  YEM: "Yemen (Saudi-backed)",
  PHL: "Philippines",
  VNM: "Viet Nam",
  BOL: "Bolivia",
  BLZ: "Belize",
  GTM: "Guatemala",
  MDV: "Maldives",
  MEX: "Mexico",
  HTI: "Haiti",
  HND: "Honduras",
  // #"EV":"El Salvador",
  MHL: "Marshall Islands",
  // #"CH":"Chad",
  // #"CD":"Cambodia",
  NRU: "Nauru",
  // // //   "FRA-NC-PF": "Pro-France New Caledonia",
  // // //   "FRA-NC-PI": "Pro-Independence New Caledonia",
  KIR: "Kiribati",
  NER: "Niger",
  NGA: "Nigeria",
  PLW: "Palau",
  // #"CI":"Côte D'Ivoire",
  HRV: "Croatia",
  GNQ: "Equatorial Guinea",
  DOM: "Dominican Republic",
  PRY: "Paraguay",
  KNA: "St. Kitts & Nevis",
  LCA: "St. Lucia",
  VCT: "St. Vincent & Grenadines",
  TUV: "Tuvalu",
  VUT: "Vanuatu",
  LBN: "Lebanon",
  // //   "LBN-HZ": "Lebanon-Hezbollah",
  // #"GH":"Ghana",
  FSM: "Micronesia",
  SOM: "Somalia",
  UGA: "Uganda",
  CAF: "Central African Republic",
  KEN: "Kenya",
  //   ABK: "Abkhazia",
  //   SOT: "South Ossetia",
  GEO: "Georgia",
  MOZ: "Mozambique",
  DJI: "Djibouti",
  ESP: "Spain",
  //   FDLR: "FDLR Tutsi Militia",
  DNK: "Denmark",
  ZWE: "Zimbabwe",
  KAZ: "Kazakhstan",
  // //   "MO-TUN": "Moldova-Transnistria",
  TZA: "Tanzania",
  // #"BN":"Burundi",
  // #"BF":"Burkina Faso",
  //   #"TJK-IRPT":"Tajik Isl. Ren.",
  //   #"TJK-PM-AFG":"Tajik Aga-Khan",
  //   #"TJK-PM-R":"Tajik Pamiri Rebels",
  //   "SOM-LKA": "Somaliland",
  // //   "LBN-TB": "Libya-Tobruk",
  // //   "LBN-TUR": "Libya-Tripoli",
};
export const multilaterals = {
  NATO: "blue",
  OPEC: "blue",
  FRANCOSPHERE: "",
  OAS: "",
  ASEAN: "",
  MERCOSUR: "",
  EA: "",
  OPECPLUS: "blue",
  G7: "blue",
  G20: "blue",
  SCO: "teal",
  CSTO: "pink",
  BRICS: "green",
  OTS: "red",
  MUSLIMBROTHERHOOD: "lime",
  AFRICANUNION: "lime",
  ARABLEAGUE: "lime",
  COMMONWEALTH: "gold",
};
// # const connColors={
// #     -1:'tab:red',
// #     0:'black',
// #     1:'tab:blue',
// # }
export const bilateralRelations: BilateralRelation[] = [
  ["GUY", "VCT", 1],
  ["SSD", "UGA", 1],
  // //   ["CMR-ARM", "NGA-BF", 1],
  // //   ["CMR-ARM", "CMR", -1],
  //   ["NGA-BF", "FRA", 1],
  //   ["NGA-BF", "GBR", 1],
  // //   ["NGA-BF", "NGA", -1],
  ["FRA", "UKR", 1],
  ["KAZ", "RUS", 0],
  ["KAZ", "TUR", 1],
  ["KAZ", "AZE", 1],
  ["AZE", "GEO", 1],
  ["KAZ", "GEO", 1],
  ["USA", "GNQ", 1],
  ["TKM", "CHN", 1],
  ["TKM", "TUR", 1],
  ["TKM", "KAZ", 1],
  ["IRN", "AFG", -1],
  ["TKM", "AFG", 1],
  ["TKM", "KGZ", 1],
  ["USA", "MDV", 1],
  ["LKA", "MDV", 1],
  //   ["KO", "MDV", 1],
  ["CHN", "MDV", 1],
  ["IND", "MDV", 1],
  ["IND", "MAR", 1],
  //   ["AZE", "LBN-TB", 1],
  // //   ["SLB", "SLB-M", -1],
  //   ["TWN", "SLB-M", 1],
  // // //   ["FRA", "FRA-NC-PI", -1],
  // //   ["FRA", "FRA-NC-PF", 1],
  //   ["LBN-HZ", "LBN", 0],
  //   ["LBN-HZ", "IRN", 1],
  // //   ["LBN-HZ", "ISR", -1],
  //   ["LBN-HZ", "PSE", 1],
  // //   ["CHL-RN", "CHL", -1],
  ["PSE", "CHL", 1],
  //   ["PNG-BGR", "FJI", 1],
  //   ["PNG-BGR", "SLB", 1],
  ["CHN", "FJI", 1],
  ["NZL", "FJI", -1],
  ["AUS", "FJI", -1],
  ["MAR", "USA", 1],
  ["CAF", "RUS", 1],
  //   ["AZE", "AH", -1],
  //   ["ARM", "AH", 1],
  ["JPN", "PLW", 1],
  ["JPN", "TWN", 1],
  //   ["RUS", "AH", 1],
  //   ["MO-TUN", "AH", 1],
  //   ["RUS", "MO-TUN", 1],
  //   ["SOT", "MO-TUN", 1],
  //   ["ABK", "MO-TUN", 1],
  //   ["ABK", "SOT", 1],
  //   ["ABK", "AH", 1],
  //   ["SOT", "AH", 1],
  //   ["ABK", "SYR", 1],
  //   ["SOT", "SYR", 1],
  //   ["ABK", "NRU", 1],
  //   ["SOT", "NRU", 1],
  //   ["ABK", "NIC", 1],
  //   ["SOT", "NIC", 1],
  //   ["ABK", "VEN", 1],
  //   ["SOT", "VEN", 1],
  //   ["ABK", "RUS", 1],
  //   ["SOT", "RUS", 1],
  ["USA", "GEO", 1],
  //   ["ABK", "GEO", -1],
  //   ["SOT", "GEO", -1],
  ["ESH", "VUT", 1],
  ["ESH", "VNM", 1],
  ["ESH", "RWA", 1],
  ["ESH", "PRK", 1],
  //   ["ESH", "SOT", 1],
  //   ["ESH", "ABK", 1],
  //   ["DNK", "SOM-LKA", 1],
  //   ["SOM", "KO", 1],
  //   ["DJI", "KO", 1],
  //   ["DJI", "SOM-LKA", 1],
  //   ["ARE", "SOM-LKA", 1],
  //   ["ETH", "SOM-LKA", 1],
  //   ["KEN", "SOM-LKA", 1],
  // //   ["PAK-BL", "PAK", -1],
  // //   ["PAK-BL", "CHN", -1],
  //   # ["IRN-BL","IRN",-1],
  // //   ["AFG-BL", "AFG", -1],
  //   ["TUR", "SOM-LKA", 1],
  //   ["SOM", "SOM-LKA", 0],
  ["SOM", "USA", 1],
  //   ["TWN", "SOM-LKA", 1],
  ["TWN", "BLZ", 1],
  ["TWN", "GTM", 1],
  ["TWN", "HTI", 1],
  ["EGY", "TZA", 1],
  ["CHN", "TZA", 1],
  ["TWN", "HND", 1],
  ["NZL", "KIR", 1],
  //   ["ESP", "KO", -1],
  //   ["EGY", "KO", 1],
  //   ["NIC", "KO", 1],
  //   ["CYP", "KO", -1],
  ["ESP", "SAU", 1],
  //   ["VNM", "KO", -1],
  //   ["UKR", "KO", -1],
  //   ["ARG", "KO", -1],
  //   ["ARM", "KO", -1],
  //   ["AZE", "KO", -1],
  //   ["IND", "KO", -1],
  //   ["TWN", "KO", 1],
  ["CHN", "NZL", 0],
  ["AUS", "NZL", 1],
  ["AUS", "KIR", 1],
  ["AUS", "PLW", 1],
  ["AUS", "FSM", 1],
  //   ["KO", "SLB", -1],
  //   ["KO", "CAF", -1],
  //   ["KO", "PNG", -1],
  //   ["KO", "FSM", 1],
  //   ["KO", "VUT", 1],
  ["AUS", "VUT", 1],
  //   ["IDN-WP", "VUT", 1],
  ["USA", "PLW", 1],
  ["USA", "FSM", 1],
  ["USA", "DOM", 1],
  ["USA", "MHL", 1],
  ["TWN", "MHL", 1],
  ["TWN", "NRU", 1],
  // //   ["USA", "JPN-RK", -1],
  ["IRN", "MLI", 1],
  //   # ["AZE","IRN-AZE",1],
  //   # ["IRN","IRN-AZE",-1],
  ["IRN", "SAU", -1],
  //   ["KO", "DNK", 1],
  //   ["KO", "NRU", -1],
  ["AUS", "NRU", 1],
  ["TWN", "PLW", 1],
  ["TWN", "PRY", 1],
  //   ["KO", "KNA", 1],
  ["TWN", "KNA", 1],
  //   ["KO", "LCA", 1],
  //   ["KO", "NIC", 1],
  //   ["KO", "NGA", -1],
  //   ["KO", "CHN", -1],
  //   ["KO", "TUV", 1],
  //   ["KO", "BGD", 1],
  ["TWN", "LCA", 1],
  ["TWN", "VCT", 1],
  ["TWN", "TUV", 1],
  ["BOL", "RUS", 1],
  ["BOL", "VEN", 1],
  ["BOL", "CUB", 1],
  ["THA", "USA", 0],
  ["TJK", "PAK", 1],
  ["TJK", "AFG", -1],
  // //   ["AFG-PJ", "AFG", -1],
  //   ["AFG-PJ", "USA", 1],
  ["AFG", "RUS", 1],
  ["NER", "FRA", 1],
  ["NER", "MLI", -1],
  ["THA", "CHN", 0],
  ["AUS", "IDN", 1],
  ["USA", "ARM", 1],
  ["USA", "AZE", 1],
  ["BGR", "GRC", 1],
  ["PNG", "IDN", 1],
  //   ["MHL", "IDN-WP", 1],
  //   ["NRU", "IDN-WP", 1],
  //   ["PLW", "IDN-WP", 1],
  //   ["TUV", "IDN-WP", 1],
  //   ["VUT", "IDN-WP", 1],
  //   ["SLB", "IDN-WP", 1],
  // //   ["IDN", "IDN-WP", -1],
  ["AUS", "UKR", 1],
  ["TJK", "KGZ", -1],
  ["TJK", "IRN", 1],
  ["KGZ", "TUR", 1],
  ["TJK", "TUR", 1],
  ["AUS", "CHN", -1],
  ["CHN", "SLB", 1],
  // //   ["FRA-NC-PI", "SLB", 1],
  ["PSE", "QAT", 1],
  ["AUS", "SLB", 0],
  ["AUS", "USA", 1],
  ["USA", "ISR", 1],
  ["IRN", "ISR", -1],
  ["USA", "CUB", -1],
  ["USA", "VEN", -1],
  ["USA", "NIC", -1],
  ["USA", "COL", 1],
  ["VEN", "COL", 1],
  ["VEN", "CUB", 1],
  ["VEN", "NIC", 1],
  ["VEN", "IRN", 1],
  ["CUB", "NIC", 1],
  ["CUB", "TUR", 1],
  ["CUB", "CHN", 1],
  ["MKD", "GRC", -1],
  ["MKD", "BGR", -1],
  //   ["USA", "MMR-NUG", 1],
  // //   ["MMR", "MMR-NUG", -1],
  ["GBR", "RUS", -1],
  //   ["MMR", "RUS", 1],
  // //   ["IRN-MEK", "IRN", -1],
  //   ["IRN-MEK", "ALB", 1],
  //   ["KO", "ALB", 1],
  //   ["KO", "GRC", -1],
  //   ["KO", "RUS", -1],
  ["TUR", "ALB", 1],
  ["IRN", "ALB", -1],
  ["ISR", "PSE", -1],
  ["IRN", "PSE", 1],
  //   ["KO", "QAT", 1],
  //   ["KO", "GUY", 1],
  //   ["KO", "ISR", 1],
  ["AZE", "ISR", 1],
  ["SAU", "USA", 1],
  ["SAU", "YEM", 1],
  ["MLI", "FRA", -1],
  ["ARM", "FRA", 1],
  ["USA", "FRA", 1],
  ["GBR", "FRA", 0],
  // //   ["MLI", "MLI-TUR", -1],
  // //   ["MMR", "MMR-KAR", -1],
  // //   ["MMR", "MMR-RAK", -1],
  // //   ["MMR", "MMR-KAC", -1],
  ["MLI", "RUS", 1],
  ["ISR", "GRC", 1],
  ["CYP", "GRC", 1],
  //   ["CYP-TRNC", "AZE", 1],
  //   ["CYP-TRNC", "TUR", 1],
  // //   ["CYP-TRNC", "CYP", -1],
  ["ARE", "YEM", 1],
  // //   ["YEM-H", "YEM", -1],
  // //   ["YEM-H", "ARE", -1],
  // //   ["YEM-H", "SAU", -1],
  //   ["YEM-H", "IRN", 1],
  // //   ["COD", "COD-M23", -1],
  ["RWA", "USA", 1],
  //   ["RWA", "COD-M23", 1],
  ["RWA", "COD", -1],
  //   ["RWA", "FDLR", -1],
  ["USA", "GRC", 1],
  //   ["KO", "SRB", -1],
  ["RUS", "SRB", 1],
  // // //   ["BiH-SRB", "BiH-HRV", -1],
  //   ["HRV", "BiH-HRV", 1],
  //   ["BiH-SRB", "SRB", 1],
  //   ["KO", "USA", 1],
  ["ARE", "ISR", 1],
  ["ARE", "IRN", -1],
  //   ["KO", "IRN", -1],
  ["USA", "IRN", -1],
  ["USA", "VNM", 1],
  ["USA", "AFG", -1],
  ["USA", "ZWE", -1],
  ["CHN", "ZWE", 1],
  ["GBR", "TUR", 1],
  ["GBR", "ZWE", -1],
  ["RUS", "VNM", 1],
  ["USA", "PHL", 1],
  ["PHL", "RUS", 1],
  ["PHL", "CHN", -1],
  ["EGY", "ETH", -1],
  ["ARE", "ETH", 1],
  ["SSD", "ETH", 1],
  ["SSD", "USA", 1],
  // //   ["ETH-TI", "ETH", -1],
  //   ["ETH-TI", "USA", 1],
  ["EGY", "GRC", 1],
  ["TUN", "DZA", 1],
  // //   ["SDN-P", "SDN", -1],
  //   ["KO", "SDN", -1],
  ["UKR", "USA", 1],
  //   ["SDN-P", "USA", 1],
  ["DZA", "ESH", 1],
  ["MAR", "ESH", -1],
  ["DZA", "MAR", -1],
  ["DZA", "RUS", 1],
  ["MAR", "ISR", 1],
  ["IRN", "RUS", 1],
  ["IND", "ARM", 1],
  ["PAK", "ARM", -1],
  ["PAK", "IND", -1],
  ["RUS", "IND", 1],
  ["PAK", "AZE", 1],
  ["IRN", "ARM", 1],
  ["AZE", "ARM", -1],
  ["AZE", "TUR", 1],
  ["UKR", "FRA", 1],
  ["UKR", "TUR", 1],
  ["UKR", "RUS", -1],
  ["USA", "RUS", -1],
  ["TUR", "GRC", -1],
  ["TUR", "EGY", 1],
  ["SYR", "USA", -1],
  ["SYR", "IRN", 1],
  //   # ["SYR-K","SYR",-1],
  //   # ["SYR-K","USA",1],
  //   # ["SYR-K","TUR",-1],
  //   # ["SYR-K","IRN",-1],
  //   # ["IRQ-K","IRQ",0],
  // //   ["IRQ-K", "SYR-K", 1],
  //   # ["IRQ-K","TUR",-1],
  ["PAK", "IRN", 1],
  ["IND", "IRN", 1],
  //   # ["IRQ-K","IRN",-1],
  //   # ["IRQ-K","USA",1],
  ["SYR", "RUS", 1],
  ["SYR", "ISR", -1],
  // // //   ["LBN-TB", "LBN-TUR", -1],
  //   ["LBN-TUR", "TUR", 1],
  //   ["LBN-TUR", "QAT", 1],
  //   ["LBN-TUR", "PAK", 1],
  //   ["LBN-TUR", "IRN", 1],
  //   ["LBN-TUR", "MAR", 1],
  //   ["LBN-TUR", "DZA", 1],
  //   ["LBN-TB", "GRC", 1],
  //   ["LBN-TB", "EGY", 1],
  //   ["LBN-TB", "ARE", 1],
  //   ["LBN-TB", "SYR", 1],
  //   ["LBN-TB", "SAU", 1],
  //   ["LBN-TB", "FRA", 1],
  //   ["LBN-TB", "RUS", 1],
  //   ["KO", "HRV", 1],
  //   ["KO", "CMR", -1],
  //   ["KO", "COD", -1],
  //   ["KO", "ARG", -1],
  //   ["KO", "CHN-ETIM", 1],
  //   ["KO", "BLZ", 1],
  //   ["KO", "MHL", 1],
  ["CHN", "SRB", 1],
  ["CHN", "IND", -1],
  //   ["KO", "IND", -1],
  //   ["KO", "PAK", 1],
  //   ["KO", "MKD", 1],
  ["ISR", "TUR", 1],
  ["CHN", "RUS", 1],
  ["CHN", "PRK", 1],
  // //   ["CHN", "CHN-ETIM", -1],
  ["CHN", "TWN", -1],
  //   ["USA", "CHN-ETIM", 1],
  ["USA", "TWN", 1],
  ["USA", "CHN", -1],
  ["USA", "PRK", -1],
  ["RUS", "PRK", 1],
  ["USA", "KOR", 1],
  ["PRK", "KOR", -1],
  ["PRK", "JPN", -1],
  ["HTI", "DOM", -1],
  ["CUB", "MEX", 1],
  ["BGD", "PAK", -1],
  ["BGD", "MMR", 1],
  ["AFG", "ARE", 1],
  ["CHN", "GNQ", 1],
  ["PNG", "AUS", 1],
  ["PSE", "CHN", 1],
  ["QAT", "CHN", 1],
  ["IRN", "CHN", 1],
  ["ARE", "CHN", 1],
  ["ARE", "SDN", 1],
  ["MOZ", "AGO", 1],
  ["MOZ", "UGA", 1],
  ["MOZ", "USA", 1],
  ["MOZ", "RUS", 1],
  ["MOZ", "RWA", 1],
  ["ESP", "ESH", -1],
  ["ESP", "ESH", -1],
  ["ESP", "MAR", 1],
  ["PER", "ESH", -1],
  ["PER", "MAR", 1],
  ["CAF", "RWA", 1],
  ["SAU", "CHN", 1],
  ["PNG", "CHN", 1],
  // //   ["PNG", "PNG-BGR", -1],
  ["KOR", "JPN", 1],
  ["VEN", "GUY", -1],
];
